//
// Created by andor on 2020/12/22.
//

#ifndef UE4_CONSOLE_H
#define UE4_CONSOLE_H
#define ROS_FATAL(...)
#define ROS_FATAL_STREAM(args)
#define ROS_FATAL_NAMED(name, ...)
#define ROS_FATAL_STREAM_NAMED(name, args)
#define ROS_FATAL_COND(cond, ...)
#define ROS_FATAL_STREAM_COND(cond, args)
#define ROS_FATAL_COND_NAMED(cond, name, ...)
#define ROS_FATAL_STREAM_COND_NAMED(cond, name, args)
#define ROS_FATAL_ONCE(...)
#define ROS_FATAL_STREAM_ONCE(args)
#define ROS_FATAL_ONCE_NAMED(name, ...)
#define ROS_FATAL_STREAM_ONCE_NAMED(name, args)
#define ROS_FATAL_THROTTLE(period, ...)
#define ROS_FATAL_STREAM_THROTTLE(period, args)
#define ROS_FATAL_THROTTLE_NAMED(period, name, ...)
#define ROS_FATAL_STREAM_THROTTLE_NAMED(period, name, args)
#define ROS_FATAL_DELAYED_THROTTLE(period, ...)
#define ROS_FATAL_STREAM_DELAYED_THROTTLE(period, args)
#define ROS_FATAL_DELAYED_THROTTLE_NAMED(period, name, ...)
#define ROS_FATAL_STREAM_DELAYED_THROTTLE_NAMED(period, name, args)
#define ROS_FATAL_FILTER(filter, ...)
#define ROS_FATAL_STREAM_FILTER(filter, args)
#define ROS_FATAL_FILTER_NAMED(filter, name, ...)
#define ROS_FATAL_STREAM_FILTER_NAMED(filter, name, args)
#define ROS_ERROR(...)
#define ROS_ERROR_STREAM(args)
#define ROS_ERROR_NAMED(name, ...)
#define ROS_ERROR_STREAM_NAMED(name, args)
#define ROS_ERROR_COND(cond, ...)
#define ROS_ERROR_STREAM_COND(cond, args)
#define ROS_ERROR_COND_NAMED(cond, name, ...)
#define ROS_ERROR_STREAM_COND_NAMED(cond, name, args)
#define ROS_ERROR_ONCE(...)
#define ROS_ERROR_STREAM_ONCE(args)
#define ROS_ERROR_ONCE_NAMED(name, ...)
#define ROS_ERROR_STREAM_ONCE_NAMED(name, args)
#define ROS_ERROR_THROTTLE(period, ...)
#define ROS_ERROR_STREAM_THROTTLE(period, args)
#define ROS_ERROR_THROTTLE_NAMED(period, name, ...)
#define ROS_ERROR_STREAM_THROTTLE_NAMED(period, name, args)
#define ROS_ERROR_DELAYED_THROTTLE(period, ...)
#define ROS_ERROR_STREAM_DELAYED_THROTTLE(period, args)
#define ROS_ERROR_DELAYED_THROTTLE_NAMED(period, name, ...)
#define ROS_ERROR_STREAM_DELAYED_THROTTLE_NAMED(period, name, args)
#define ROS_ERROR_FILTER(filter, ...)
#define ROS_ERROR_STREAM_FILTER(filter, args)
#define ROS_ERROR_FILTER_NAMED(filter, name, ...)
#define ROS_ERROR_STREAM_FILTER_NAMED(filter, name, args)
#define ROS_WARN(...)
#define ROS_WARN_STREAM(args)
#define ROS_WARN_NAMED(name, ...)
#define ROS_WARN_STREAM_NAMED(name, args)
#define ROS_WARN_COND(cond, ...)
#define ROS_WARN_STREAM_COND(cond, args)
#define ROS_WARN_COND_NAMED(cond, name, ...)
#define ROS_WARN_STREAM_COND_NAMED(cond, name, args)
#define ROS_WARN_ONCE(...)
#define ROS_WARN_STREAM_ONCE(args)
#define ROS_WARN_ONCE_NAMED(name, ...)
#define ROS_WARN_STREAM_ONCE_NAMED(name, args)
#define ROS_WARN_THROTTLE(period, ...)
#define ROS_WARN_STREAM_THROTTLE(period, args)
#define ROS_WARN_THROTTLE_NAMED(period, name, ...)
#define ROS_WARN_STREAM_THROTTLE_NAMED(period, name, args)
#define ROS_WARN_DELAYED_THROTTLE(period, ...)
#define ROS_WARN_STREAM_DELAYED_THROTTLE(period, args)
#define ROS_WARN_DELAYED_THROTTLE_NAMED(period, name, ...)
#define ROS_WARN_STREAM_DELAYED_THROTTLE_NAMED(period, name, args)
#define ROS_WARN_FILTER(filter, ...)
#define ROS_WARN_STREAM_FILTER(filter, args)
#define ROS_WARN_FILTER_NAMED(filter, name, ...)
#define ROS_WARN_STREAM_FILTER_NAMED(filter, name, args)
#define ROS_INFO(...)
#define ROS_INFO_STREAM(args)
#define ROS_INFO_NAMED(name, ...)
#define ROS_INFO_STREAM_NAMED(name, args)
#define ROS_INFO_COND(cond, ...)
#define ROS_INFO_STREAM_COND(cond, args)
#define ROS_INFO_COND_NAMED(cond, name, ...)
#define ROS_INFO_STREAM_COND_NAMED(cond, name, args)
#define ROS_INFO_ONCE(...)
#define ROS_INFO_STREAM_ONCE(args)
#define ROS_INFO_ONCE_NAMED(name, ...)
#define ROS_INFO_STREAM_ONCE_NAMED(name, args)
#define ROS_INFO_THROTTLE(period, ...)
#define ROS_INFO_STREAM_THROTTLE(period, args)
#define ROS_INFO_THROTTLE_NAMED(period, name, ...)
#define ROS_INFO_STREAM_THROTTLE_NAMED(period, name, args)
#define ROS_INFO_DELAYED_THROTTLE(period, ...)
#define ROS_INFO_STREAM_DELAYED_THROTTLE(period, args)
#define ROS_INFO_DELAYED_THROTTLE_NAMED(period, name, ...)
#define ROS_INFO_STREAM_DELAYED_THROTTLE_NAMED(period, name, args)
#define ROS_INFO_FILTER(filter, ...)
#define ROS_INFO_STREAM_FILTER(filter, args)
#define ROS_INFO_FILTER_NAMED(filter, name, ...)
#define ROS_INFO_STREAM_FILTER_NAMED(filter, name, args)
#define ROS_DEBUG(...)
#define ROS_DEBUG_STREAM(args)
#define ROS_DEBUG_NAMED(name, ...)
#define ROS_DEBUG_STREAM_NAMED(name, args)
#define ROS_DEBUG_COND(cond, ...)
#define ROS_DEBUG_STREAM_COND(cond, args)
#define ROS_DEBUG_COND_NAMED(cond, name, ...)
#define ROS_DEBUG_STREAM_COND_NAMED(cond, name, args)
#define ROS_DEBUG_ONCE(...)
#define ROS_DEBUG_STREAM_ONCE(args)
#define ROS_DEBUG_ONCE_NAMED(name, ...)
#define ROS_DEBUG_STREAM_ONCE_NAMED(name, args)
#define ROS_DEBUG_THROTTLE(period, ...)
#define ROS_DEBUG_STREAM_THROTTLE(period, args)
#define ROS_DEBUG_THROTTLE_NAMED(period, name, ...)
#define ROS_DEBUG_STREAM_THROTTLE_NAMED(period, name, args)
#define ROS_DEBUG_DELAYED_THROTTLE(period, ...)
#define ROS_DEBUG_STREAM_DELAYED_THROTTLE(period, args)
#define ROS_DEBUG_DELAYED_THROTTLE_NAMED(period, name, ...)
#define ROS_DEBUG_STREAM_DELAYED_THROTTLE_NAMED(period, name, args)
#define ROS_DEBUG_FILTER(filter, ...)
#define ROS_DEBUG_STREAM_FILTER(filter, args)
#define ROS_DEBUG_FILTER_NAMED(filter, name, ...)
#define ROS_DEBUG_STREAM_FILTER_NAMED(filter, name, args)
#endif //UE4_CONSOLE_H
